name: Nightly RPM Build - Master Branch
on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  call-master-rpm-build-and-upload:
    uses: ./.github/workflows/rpm-build-and-upload-flow.yaml
    secrets: inherit
    with:
      branch: 'master'
